services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener
    ports:
      - "5432:5432"
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urlshortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  urlshortener:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://urlshortener:urlshortener@postgres:5432/urlshortener
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: your-secret-key-here
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests 